const trialUsers = [
  {
    uuid: "7249e565-4dfc-4a38-9582-f4b0f2da3dba",
    firstName: "Scott",
    lastName: "Smith",
    field4: "",
    email: "ssmith@smithball.com",
    city: "Palm Beach Gardens",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-061",
  },
  {
    uuid: "5a543c34-bad3-49d0-a13d-7de4661b3782",
    firstName: "Curtis",
    lastName: "Mase",
    field4: "",
    email: "cmase@maselaw.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-062",
  },
  {
    uuid: "f8733245-676b-403c-b535-fc642dacff8c",
    firstName: "Brett",
    lastName: "Rosen",
    field4: "",
    email: "brosen@goldbergandrosen.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-063",
  },
  {
    uuid: "ac6d1fe8-5a4c-42a9-b163-684b9385a727",
    firstName: "Rachel",
    lastName: "Tuckerman",
    field4: "",
    email: "rachtuckerman@gmail.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-064",
  },
  {
    uuid: "776b0f59-646e-48f5-b5f4-5d8b4eef66d2",
    firstName: "Deborah",
    lastName: "Daly",
    field4: "",
    email: "deborahd@ha.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-065",
  },
  {
    uuid: "00dcc023-6432-4e77-b7c4-7e928ccee977",
    firstName: "Timothy",
    lastName: "Shanahan",
    field4: "",
    email: "tim@bernsteininjurylaw.com",
    city: "Tampa",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-066",
  },
  {
    uuid: "eca54566-a90e-4388-8c87-0b9429020ff2",
    firstName: "Jennifer",
    lastName: "Englert",
    field4: "",
    email: "jenglert@theorlandolawgroup.com",
    city: "Orlando",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-067",
  },
  {
    uuid: "d4fa78d7-8617-4eab-bf74-02619800e78b",
    firstName: "Aaron",
    lastName: "Lapin",
    field4: "",
    email: "aaron@lapininjurylaw.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-068",
  },
  {
    field1: "66f567f2-dd6e-4347-a53c-1de900a3df42",
    firstName: "Harsh",
    lastName: "Arora",
    field4: "",
    email: "harsh.arora@nelsonmullins.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-069",
  },
  {
    uuid: "b70eb3ae-2695-453d-80cb-cb7488329726",
    firstName: "Spencer",
    lastName: "Kuvin",
    field4: "",
    email: "skuvin@goldlaw.com",
    city: "West Palm Beach",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-070",
  },
  {
    uuid: "46d3b0cb-3008-4b5e-be05-a329a536ccd1",
    firstName: "Matthew",
    lastName: "Thomas",
    field4: "",
    email: "matthew@gravesthomas.com",
    city: "Vero Beach",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-071",
  },
  {
    field1: "b72c7c06-edcb-4eeb-bd5e-87912a6ed722",
    firstName: "Philip",
    lastName: "Freiden",
    field4: "",
    email: "pf@fblawyers.net",
    city: "Miami",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-072",
  },
  {
    uuid: "3c863814-cd8e-437c-9435-a291a0d37ada",
    firstName: "Mariano",
    lastName: "Garcia",
    field4: "",
    email: "mxg@searcylaw.com",
    city: "West Palm Beach",
    fieldstate7: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-073",
  },
  {
    field1: "8e6d5916-9168-4312-b955-ec983a38a47b",
    firstName: "Benjamin",
    lastName: "Grossman",
    field4: "",
    email: "bjgrossman@foley.com",
    city: "Tallahassee",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-074",
  },
  {
    uuid: "05ddc49c-d3d4-4278-84be-9dd61577102e",
    firstName: "Armondo",
    lastName: "Edmiston",
    field4: "",
    email: "armando@armandoinjurylaw.com",
    city: "Tampa",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-075",
  },
  {
    field1: "36d56dec-3222-4cf0-b3b7-61d1cbba761a",
    firstName: "Michael",
    lastName: "McLeod",
    field4: "",
    email: "mmcleod@mcleodbrock.com",
    city: "Boca Raton",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-076",
  },
  {
    field1: "2fe8a674-f03e-4e90-80a9-d38142af57f3",
    firstName: "Paul",
    lastName: "Perkins",
    field4: "",
    email: "pperkins@paulandperkins.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-077",
  },
  {
    uuid: "7c471377-640b-4261-9a5d-24d0c67c6d66",
    firstName: "Sally",
    lastName: "Fox",
    field4: "",
    email: "sfox@esclaw.com",
    city: "Pensacola",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-078",
  },
  {
    uuid: "8c5b9f93-68b4-4169-9d03-e3e2b3fe95f3",
    firstName: "Christian",
    lastName: "Searcy",
    field4: "",
    email: "cds@searcylaw.com",
    city: "West Palm Beach",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-079",
  },
  {
    uuid: "9cf0953f-3dd2-4df3-8300-ff6d28f7302c",
    firstName: "David",
    lastName: "Paul",
    field4: "",
    email: "dave@pkblawfirm.com",
    city: "Winter Park",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-080",
  },
  {
    uuid: "2534523b-24a0-4c69-a90c-c16a2f9d68ee",
    firstName: "David",
    lastName: "Paul",
    field4: "",
    email: "david@rvplawyers.com",
    city: "Miami",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-081",
  },
  {
    uuid: "f31ba35e-7a52-400d-bd9f-54ff2c34b98c",
    firstName: "Carlos",
    lastName: "Leach",
    field4: "",
    email: "cleach@theleachfirm.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-082",
  },
  {
    uuid: "15798053-4b17-4fe6-9a85-525874d94aac",
    firstName: "Steven",
    lastName: "Lavely",
    field4: "",
    email: "steve@lavelylaw.com",
    city: "Bradenton",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-083",
  },
  {
    uuid: "22401c49-dadf-4ad7-82c9-c9b74b0c7159",
    firstName: "Fuller",
    lastName: "Haring",
    field4: "",
    email: "fuller.haring@boginmunns.com",
    city: "Longwood",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-084",
  },
  {
    uuid: "cfe67163-e55a-496b-9ba3-a9ecc3b3d785",
    firstName: "Drew",
    lastName: "McCulloch",
    field4: "",
    email: "drew@mcfloridalaw.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-085",
  },
  {
    uuid: "7e697bbb-5329-4ad3-9f81-da8da51a818a",
    firstName: "Richard",
    lastName: "Welden",
    field4: "",
    email: "rweldonlaw@gmail.com",
    city: "Safety Harbor",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-086",
  },
  {
    field1: "6df72490-3b67-4a05-ac29-7346cc4de52d",
    firstName: "Darryl",
    lastName: "Richards",
    firm: "***",
    email: "darrylr@jpfirm.com",
    city: "",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-087",
  },
  {
    uuid: "99dedcf5-5a16-42a7-ab0b-a52f62e187ae",
    firstName: "Ross",
    lastName: "Abramowitz",
    firm: "The Injury Firm",
    email: "ross@flinjuryfirm.com",
    city: "Fort Lauderdale",
    state: "Florida",
    zip: "",
    signupCode: "novofreedom-fl24-089",
  },
  {
    uuid: "99dedcf5-5a16-42a7-ab0b-a52f62e187ae",
    firstName: "Dalton",
    lastName: "Thomas",
    firm: "The Injury Firm",
    email: "dalton@flinjuryfirm.com",
    city: "Fort Lauderdale",
    state: "Florida",
    zip: "33334",
    signupCode: "novofreedom-fl24-090",
  },
  {
    firstName: "First Name",
    lastName: "Last Name",
    firm: "Firm",
    email: "Email",
    city: "City",
    state: "State",
    signupCode: "novolens-nj24-202",
  },
  {
    firstName: "Kristy",
    lastName: "Krasowski",
    firm: "Brandon J. Broderick, Personal Injury Attorneys",
    email: "kristy.krasowski@brandonjbroderick.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-203",
  },
  {
    firstName: "Ken",
    lastName: "Biedzynski",
    firm: "Goldzweig, Green, Eiger & Biedzynski, LLC",
    email: "kenbiedzynski@attorneys.com",
    city: "River Edge",
    state: "NJ",
    signupCode: "novolens-nj24-204",
  },
  {
    firstName: "Steven",
    lastName: "Benvenisti",
    firm: "Davis, Saperstein & Salomon, P.C.",
    email: "steven@dsslaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-205",
  },
  {
    firstName: "Adam",
    lastName: "Lederman",
    firm: "Davis, Saperstein & Salomon, P.C.",
    email: "adaml@dsslaw.com",
    city: "Teaneck",
    state: "NJ",
    signupCode: "novolens-nj24-206",
  },
  {
    firstName: "Tiffany",
    lastName: "Burress",
    firm: "Brandon J. Broderick, Personal Injury Attorneys",
    email: "tburress@brandonjbroderick.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-207",
  },
  {
    firstName: "Angelo",
    lastName: "Catanzariti",
    firm: "Corradino & Papa",
    email: "angelocatanzariti@corradinoandpapa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-208",
  },
  {
    firstName: "Joseph",
    lastName: "DeFuria",
    firm: "Corradino & Papa",
    email: "jdefuria@corradinoandpapa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-209",
  },
  {
    firstName: "Alex",
    lastName: "Lyubarsky",
    firm: "Wilentz, Goldman & Spitzer",
    email: "alyubarsky@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-210",
  },
  {
    firstName: "Lynne",
    lastName: "Kizis",
    firm: "Wilentz, Goldman & Spitzer",
    email: "lkizis@wilentz.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-211",
  },
  {
    firstName: "Jason",
    lastName: "Krisza",
    firm: "Wilentz, Goldman & Spitzer",
    email: "",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-212",
  },
  {
    firstName: "Jay",
    lastName: "Sawczak",
    firm: "Wilentz, Goldman & Spitzer",
    email: "jsawczak@wilentz.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-213",
  },
  {
    firstName: "Pierre",
    lastName: "Chwang",
    firm: "Wilentz, Goldman & Spitzer",
    email: "pchwang@wilentz.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-214",
  },
  {
    firstName: "Yessica",
    lastName: "Pinales",
    firm: "",
    email: "ypinales@wilentz.com",
    city: "",
    state: "NY",
    signupCode: "novolens-nj24-215",
  },
  {
    firstName: "Michael",
    lastName: "Ellery",
    firm: "Console & Associates P.C.",
    email: "mellery@myinjuryattorney.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-216",
  },
  {
    firstName: "Lindsay",
    lastName: "Sewekow",
    firm: "Console & Associates P.C.",
    email: "lsewekow@myinjuryattorney.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-217",
  },
  {
    firstName: "Katherine",
    lastName: "Catanese",
    firm: "Folew & Lardner, LLP",
    email: "katherine.catanese@foley.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-218",
  },
  {
    firstName: "Rachel",
    lastName: "Placitella",
    firm: "Cohen, Placitella & Roth",
    email: "rplacitella@cprlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-219",
  },
  {
    firstName: "Michael",
    lastName: "Dennin",
    firm: "Law Offices of Vincent J Ciecka, P.C.",
    email: "mdennin@ciecka.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-220",
  },
  {
    firstName: "Vincent",
    lastName: "Ciecka",
    firm: "Law Offices of Vincent J Ciecka, P.C.",
    email: "vciecka@ciecka.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-221",
  },
  {
    firstName: "Santo",
    lastName: "Artusa",
    firm: "Artusa ALw Firm",
    email: "santoartusa@gmail.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-222",
  },
  {
    firstName: "Scott",
    lastName: "Grossman",
    firm: "The Grossman Law Firm",
    email: "scottgrossman@grossmanlaw.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-223",
  },
  {
    firstName: "Adam",
    lastName: "Malamut",
    firm: "Malamut & Associates",
    email: "adam@malamutlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-224",
  },
  {
    firstName: "Katherine",
    lastName: "Paton",
    firm: "The Paton Law Firm",
    email: "kimberly@patonlawfirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-225",
  },
  {
    firstName: "Scott",
    lastName: "Sheldon",
    firm: "Malamut & Associates",
    email: "scott@malamutlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-226",
  },
  {
    firstName: "Michele",
    lastName: "Haas",
    firm: "Malamut & Associates",
    email: "michele@malamutlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-227",
  },
  {
    firstName: "Mark",
    lastName: "Natale",
    firm: "Malamut & Associates",
    email: "mnatale@malamutlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-228",
  },
  {
    firstName: "Michael",
    lastName: "Ringold",
    firm: "Dansky, Katz, Ringold & York",
    email: "ringold@njlegalhelp.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-229",
  },
  {
    firstName: "Laurie",
    lastName: "Newmark",
    firm: "Laurie Newmark",
    email: "lln@ttnlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-230",
  },
  {
    firstName: "James",
    lastName: "Drake",
    firm: "Weiss & Paarz",
    email: "jdrake@weisspaarz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-231",
  },
  {
    firstName: "Kevin",
    lastName: "Costello",
    firm: "Costello & Mains, PC",
    email: "kcostello@costellomains.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-232",
  },
  {
    firstName: "David",
    lastName: "Krolikowski",
    firm: "Weiss & Paarz",
    email: "dkrolikowski@weisspaarz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-233",
  },
  {
    firstName: "Pamela",
    lastName: "Brown-Jones",
    firm: "Weiss & Paarz",
    email: "pjones@goralkalawfirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-234",
  },
  {
    firstName: "Peter",
    lastName: "Garvey",
    firm: "Law Office of Peter Garvey",
    email: "pgarvey@obbblaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-235",
  },
  {
    firstName: "David",
    lastName: "Spevack",
    firm: "Spevack Law Firm",
    email: "davids@spevacklegalteam.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-236",
  },
  {
    firstName: "Sara",
    lastName: "McArdle",
    firm: "Law Office of Sara Sencer McArdle",
    email: "smcardle@saramcardlelaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-237",
  },
  {
    firstName: "Brian",
    lastName: "Drazen",
    firm: "Drazen and Warchaw",
    email: "brian@drazinandwarshaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-238",
  },
  {
    firstName: "Adam",
    lastName: "Kirgis",
    firm: "",
    email: "akirgis@gmail.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-239",
  },
  {
    firstName: "John",
    lastName: "Scura",
    firm: "Scuara, Wigfield, Heyer, & Stevens",
    email: "jscura@scura.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-240",
  },
  {
    firstName: "Kate",
    lastName: "Reilly",
    firm: "Brady, Brady & Reilly",
    email: "kreilly@bbr-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-241",
  },
  {
    firstName: "Jae",
    lastName: "Lee",
    firm: "Jae Lee Law",
    email: "jae@jaeleelaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-242",
  },
  {
    firstName: "Sharon",
    lastName: "Freeman",
    firm: "Nusbaum, Stein, Goldstein, Bronstein & Kron",
    email: "sharon@freeman.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-243",
  },
  {
    firstName: "Ronald",
    lastName: "Bronstein",
    firm: "Nusbaum, Stein, Goldstein, Bronstein & Kron",
    email: "ronald@nusbaumstein.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-244",
  },
  {
    firstName: "Robyn",
    lastName: "Goldenberg",
    firm: "Posternock Apell Law Firm",
    email: "robyng@posternockapell.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-245",
  },
  {
    firstName: "Diana",
    lastName: "Sever",
    firm: "Posternock Apell Law Firm",
    email: "dianas@posternockapell.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-246",
  },
  {
    firstName: "Marie",
    lastName: "Maney",
    firm: "Posternock Apell Law Firm",
    email: "mariem@posternockapell.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-247",
  },
  {
    firstName: "Robert",
    lastName: "Beck",
    firm: "Archer & Greiner, PC",
    email: "rbeck@archerlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-248",
  },
  {
    firstName: "Michael",
    lastName: "Horn",
    firm: "Archer & Greiner, PC",
    email: "mhorn@archerlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-249",
  },
  {
    firstName: "Robrta",
    lastName: "Barsotti",
    firm: "Archer & Greiner, PC",
    email: "rbarsotti@archerlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-250",
  },
  {
    firstName: "Steven",
    lastName: "Harz",
    firm: "Archer & Greiner, PC",
    email: "sharz@archerlaw.com",
    city: "Hackensack",
    state: "NJ",
    signupCode: "novolens-nj24-251",
  },
  {
    firstName: "Audrey",
    lastName: "Shields",
    firm: "Golden, Rothschild, Spagnola, Lundell, Boylan, Garubo & Bell, PC",
    email: "ashields@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-252",
  },
  {
    firstName: "Gene",
    lastName: "Killian",
    firm: "The Killian Firm",
    email: "ekillian@tkfpc.com",
    city: "MIddletown",
    state: "NJ",
    signupCode: "novolens-nj24-253",
  },
  {
    firstName: "Josh",
    lastName: "Markowitz",
    firm: "",
    email: "josh.markowitz@mgs-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-254",
  },
  {
    firstName: "Jillian",
    lastName: "Centanni",
    firm: "The JA Centanni Law Firm",
    email: "jillian.a.centanni@gmail.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-255",
  },
  {
    firstName: "Lawerence",
    lastName: "Powers",
    firm: "Hoagland, Longo",
    email: "lpowers@hoaglandlongo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-256",
  },
  {
    firstName: "Gary",
    lastName: "Hoagland",
    firm: "Hoagland, Longo",
    email: "ghoagland@hoaglandlongo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-257",
  },
  {
    firstName: "Frank",
    lastName: "Caruso",
    firm: "Hoagland, Longo",
    email: "fcaruso@hoaglandlongo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-258",
  },
  {
    firstName: "Marc",
    lastName: "Gaffey",
    firm: "Hoagland, Longo",
    email: "marc.gaffrey@hoaglandlongo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-259",
  },
  {
    firstName: "Joseph",
    lastName: "Leone",
    firm: "Hoagland, Longo",
    email: "jleone@hoaglandlongo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-260",
  },
  {
    firstName: "Charles",
    lastName: "Lanzalotti",
    firm: "Bennett, Bricklin & Saltzburg",
    email: "lanzalotti@bbs-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-261",
  },
  {
    firstName: "Michael",
    lastName: "Epstein",
    firm: "The Epstein Law Firm",
    email: "mjepstein@theepsteinlawfirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-262",
  },
  {
    firstName: "Vito",
    lastName: "Gagliardi",
    firm: "Porzio, Bromber & Newman",
    email: "vagagliardi@pbnlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-263",
  },
  {
    firstName: "Theresa",
    lastName: "Lyons",
    firm: "Lyons & Associates",
    email: "theresa.lyons@lyonspc.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-264",
  },
  {
    firstName: "Gorman",
    lastName: "John",
    firm: "Lutz, Shafranski, Gorman & Mahoney",
    email: "jgorman@lsgmpa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-265",
  },
  {
    firstName: "Daniele",
    lastName: "Cervino",
    firm: "Beattie Padovano, LLC",
    email: "dcervino@beattielaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-266",
  },
  {
    firstName: "Kenneth",
    lastName: "Bogdan",
    firm: "Conner, Strong & Buckelew",
    email: "kbogdan@connerstrong.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-267",
  },
  {
    firstName: "Paul",
    lastName: "Stanton",
    firm: "McCrosson & Stanton",
    email: "paul@mccrossonstantonlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-268",
  },
  {
    firstName: "Jonathan",
    lastName: "Rudnick",
    firm: "",
    email: "jonr@cartonandrudnick.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-269",
  },
  {
    firstName: "Esther",
    lastName: "Omoloyin",
    firm: "Goldberg Segalla",
    email: "eomoloyin@goldbergsegalla.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-270",
  },
  {
    firstName: "Abraham",
    lastName: "Milgraum",
    firm: "The Donnelly Law Firm, LLC",
    email: "abrahammilgraum@njciviljustice.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-271",
  },
  {
    firstName: "Susan",
    lastName: "Rubright",
    firm: "Brach Eichler",
    email: "srubright@bracheichler.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-272",
  },
  {
    firstName: "Kirsten",
    lastName: "Branigan",
    firm: "KSBranigan Law, PC",
    email: "kirsten@ksbraniganlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-273",
  },
  {
    firstName: "Andrew",
    lastName: "Dressel",
    firm: "Dressel/Malikschmitt LLP",
    email: "andrew@dresselmalikschmitt.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-274",
  },
  {
    firstName: "Mark",
    lastName: "Shapiro",
    firm: "Hyland, Levin Shapiro",
    email: "shapiro@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-275",
  },
  {
    firstName: "Thomas",
    lastName: "Shebell",
    firm: "Shebell & Shebell",
    email: "tshebell@shebell.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-276",
  },
  {
    firstName: "Richard",
    lastName: "Perr",
    firm: "Kaufman Dolowich, LLP",
    email: "rperr@kaufmandolowich.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-277",
  },
  {
    firstName: "Brian",
    lastName: "Schwartz",
    firm: "Szaferman Lakind",
    email: "bschwartz@szaferman.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-278",
  },
  {
    firstName: "John",
    lastName: "Vreeland",
    firm: "Genova, Burns & Giantomasi",
    email: "jvreeland@genovaburns.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-279",
  },
  {
    firstName: "Stephen",
    lastName: "Barcan",
    firm: "Wilentz, Goldman & Spitzer",
    email: "sbarcan@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-280",
  },
  {
    firstName: "Gerald",
    lastName: "Clark",
    firm: "Clark Law Firm, PC",
    email: "gclark@clarklawnj.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-281",
  },
  {
    firstName: "Staci",
    lastName: "Roccanova",
    firm: "Mikita & Roccanova",
    email: "sroccanova@mr-laws.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-282",
  },
  {
    firstName: "James",
    lastName: "Napoli",
    firm: "Caesar & Napoli",
    email: "jnapoli@caesarnapoli.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-283",
  },
  {
    firstName: "Susan",
    lastName: "Karp",
    firm: "",
    email: "skarp@murphyllp.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-284",
  },
  {
    firstName: "Joe",
    lastName: "Russel",
    firm: "Wilentz, Goldman & Spitzer",
    email: "jrussell@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-285",
  },
  {
    firstName: "Christopher",
    lastName: "Westrick",
    firm: "",
    email: "cwestrick@carellabyrne.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-286",
  },
  {
    firstName: "Mark",
    lastName: "Sadaka",
    firm: "",
    email: "mark@SadakaFirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-287",
  },
  {
    firstName: "John",
    lastName: "Novella",
    firm: "Goldberg Segalla",
    email: "jnovella@goldbergsegalla.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-288",
  },
  {
    firstName: "Megan",
    lastName: "Gable",
    firm: "Ferrara & Gable",
    email: "mgable@ferraralawfirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-289",
  },
  {
    firstName: "James",
    lastName: "Uliano",
    firm: "Chamlin Uliano & Walsh",
    email: "jjuliano@chamlinlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-290",
  },
  {
    firstName: "Patrick",
    lastName: "Falcon",
    firm: "Falcon Law Firm",
    email: "patrick@falconcpa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-291",
  },
  {
    firstName: "Nick",
    lastName: "Day",
    firm: "Day & Associates",
    email: "nday@nickdaylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-292",
  },
  {
    firstName: "James",
    lastName: "Lawlor",
    firm: "",
    email: "jameslawlor@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-293",
  },
  {
    firstName: "Eric",
    lastName: "Aretsky",
    firm: "Aretsky & Aretsky",
    email: "eric@aretskylawgroup.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-294",
  },
  {
    firstName: "Robert",
    lastName: "Bianchi",
    firm: "The Bianci Law Group",
    email: "rbianchi@bianchilawgroup.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-295",
  },
  {
    firstName: "Kevork",
    lastName: "Adanas",
    firm: "Kevork Adanas, P.C.",
    email: "george@adanaslaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-296",
  },
  {
    firstName: "Joseph",
    lastName: "Haftek",
    firm: "Schenck, Price, Smith & King",
    email: "jrh@spsk.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-297",
  },
  {
    firstName: "Rafael",
    lastName: "Vergara",
    firm: "White & Williams, LLP",
    email: "rvergara@whiteandwilliams.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-298",
  },
  {
    firstName: "Thomas",
    lastName: "Lenney",
    firm: "Williams, Graffeo & Stern LLC",
    email: "lenney@kaplanwilliams.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-299",
  },
  {
    firstName: "Lauren",
    lastName: "Komsa",
    firm: "Williams, Graffeo & Stern LLC",
    email: "komsa@kaplanwilliams.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-300",
  },
  {
    firstName: "Margaret",
    lastName: "Wood",
    firm: "",
    email: "mwood@csglaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-301",
  },
  {
    firstName: "Mark",
    lastName: "Levenson",
    firm: "Sills, Cummis & Gross, PC",
    email: "mlevenson@sillscummis.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-302",
  },
  {
    firstName: "Eugene",
    lastName: "Wilkinson",
    firm: "The Wilkinson Group",
    email: "thewilkinsongroup@gmail.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-303",
  },
  {
    firstName: "Jennifer",
    lastName: "Lazor",
    firm: "Lazor Rantas, PC",
    email: "jlazor@lazorrantas.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-304",
  },
  {
    firstName: "Kenneth",
    lastName: "Gormley",
    firm: "Fabiani Cohen & Hall, LLP",
    email: "gormleyk@fcllp.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-305",
  },
  {
    firstName: "Haley",
    lastName: "Greico",
    firm: "Lambariello, Smith & Speed",
    email: "hgrieco@lsslawoffices.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-306",
  },
  {
    firstName: "Carl",
    lastName: "Soranno",
    firm: "Brach Eichler",
    email: "",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-307",
  },
  {
    firstName: "Terrance",
    lastName: "Smith",
    firm: "",
    email: "terrences@dsslaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-308",
  },
  {
    firstName: "Jonathan",
    lastName: "D'Agostino",
    firm: "",
    email: "jdagostino@daglawteam.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-309",
  },
  {
    firstName: "Mary",
    lastName: "Millerick",
    firm: "Javerbaum Wurgaft Hicks Kahn Wikstrom & Sinins P.C. Information",
    email: "mmillerick@javerbaumwurgaft.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-310",
  },
  {
    firstName: "Mstthew",
    lastName: "Schiller",
    firm: "Murphy Partners",
    email: "mschiller@murphyllp.com",
    city: "Newark",
    state: "NJ",
    signupCode: "novolens-nj24-311",
  },
  {
    firstName: "Brian",
    lastName: "Frankoski",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "bfrankoski@pirozinnalaw.com",
    city: "NY",
    state: "NY",
    signupCode: "novolens-nj24-312",
  },
  {
    firstName: "Michael",
    lastName: "Koribanick",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "mkoribanick@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-313",
  },
  {
    firstName: "Nancy",
    lastName: "Moemen",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "nmoemen@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-314",
  },
  {
    firstName: "Alex",
    lastName: "Pastore",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "apastore@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-315",
  },
  {
    firstName: "Kristen",
    lastName: "Jones",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "kjones@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-316",
  },
  {
    firstName: "Michelle",
    lastName: "Smith",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "msmith@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-317",
  },
  {
    firstName: "Dan",
    lastName: "Bevere",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "dbevere@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-318",
  },
  {
    firstName: "David",
    lastName: "Paris",
    firm: "Piro, Zinna, Cifelli, Paris & Genitempo, LLC",
    email: "dparis@pirozinnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-319",
  },
  {
    firstName: "Rajeh",
    lastName: "Saadeh",
    firm: "Law Office of Rajeh Saadeh",
    email: "rsaadeh@rajehsaadeh.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-320",
  },
  {
    firstName: "Robert",
    lastName: "Knee",
    firm: "Knee Law Firm",
    email: "rknee@kneelaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-321",
  },
  {
    firstName: "John",
    lastName: "DeRose",
    firm: "Clark Hill Law",
    email: "jderose@clarkhill.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-322",
  },
  {
    firstName: "Steven",
    lastName: "Rosenberg",
    firm: "Danziger, Danziger & Muro",
    email: "steven.rosenberg@danziger.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-323",
  },
  {
    firstName: "Bradley",
    lastName: "Muro",
    firm: "Danziger, Danziger & Muro",
    email: "brad@danziger.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-324",
  },
  {
    firstName: "Renee",
    lastName: "Klaperman",
    firm: "Danziger, Danziger & Muro",
    email: "renee@danziger.com",
    city: "NY",
    state: "NY",
    signupCode: "novolens-nj24-325",
  },
  {
    firstName: "Richard",
    lastName: "Granofsky",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "rgranofsky@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-326",
  },
  {
    firstName: "Aoife",
    lastName: "Kavanagh",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "akavanagh@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-327",
  },
  {
    firstName: "David",
    lastName: "Motola",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "dmotola@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-328",
  },
  {
    firstName: "Robyn",
    lastName: "Leader",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "rleader@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-329",
  },
  {
    firstName: "Paul",
    lastName: "Kassirer",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "pkassirer@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-330",
  },
  {
    firstName: "Alfredo",
    lastName: "Alvarado",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "aalvarado@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-331",
  },
  {
    firstName: "Robert",
    lastName: "Dunn",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "robertdunn@lskdnylaw.com",
    city: "",
    state: "NY",
    signupCode: "novolens-nj24-332",
  },
  {
    firstName: "Richard",
    lastName: "Granofsky",
    firm: "Lester Schwab Katz & Dwyer Information",
    email: "rgranofsky@lskdnylaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-333",
  },
  {
    firstName: "Steven",
    lastName: "Goldstein",
    firm: "Goldstein & Handwerker",
    email: "steveng@ghlawnynj.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-334",
  },
  {
    firstName: "Richard",
    lastName: "Ganter",
    firm: "Cleary Giacobbe Alfieri Jacobs",
    email: "rgantner@cgajlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-335",
  },
  {
    firstName: "Joseph",
    lastName: "Rem",
    firm: "Rem Law Group",
    email: "jrem@remlawgroup.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-336",
  },
  {
    firstName: "Thomas",
    lastName: "Wehner",
    firm: "Chartwell Law Offices",
    email: "twehner@chartwelllaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-337",
  },
  {
    firstName: "James",
    lastName: "Andrews",
    firm: "",
    email: "jandrews@ghclaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-338",
  },
  {
    firstName: "Jack",
    lastName: "Gillick",
    firm: "",
    email: "jgillick@njrcmlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-339",
  },
  {
    firstName: "Meredith",
    lastName: "Stoma",
    firm: "",
    email: "meredith.stoma@lewisbrisbois.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-340",
  },
  {
    firstName: "Brian",
    lastName: "Paul",
    firm: "",
    email: "bpaul@szaferman.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-341",
  },
  {
    firstName: "Alan",
    lastName: "Schwalbe",
    firm: "",
    email: "aschwalbe@jacobslawoffice.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-342",
  },
  {
    firstName: "Ronald",
    lastName: "Abramson",
    firm: "",
    email: "rabramson@winnebanta.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-343",
  },
  {
    firstName: "Glenn",
    lastName: "Kienz",
    firm: "",
    email: "gkienz@weiner.law",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-344",
  },
  {
    firstName: "Sherri",
    lastName: "Affrunti",
    firm: "",
    email: "sherriaffrunti@reedsmith.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-345",
  },
  {
    firstName: "Jeff",
    lastName: "Horn",
    firm: "",
    email: "jhorn@hornlawgroup.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-346",
  },
  {
    firstName: "Tom",
    lastName: "Fischer",
    firm: "",
    email: "tpf@bfz-legal.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-347",
  },
  {
    firstName: "Jack",
    lastName: "Corradino",
    firm: "",
    email: "jack@corradinoandpapa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-348",
  },
  {
    firstName: "Todd",
    lastName: "Palumbo",
    firm: "",
    email: "jack@corradinoandpapa.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-349",
  },
  {
    firstName: "Michael",
    lastName: "Zicherman",
    firm: "",
    email: "mzicherman@pecklaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-350",
  },
  {
    firstName: "Donald",
    lastName: "Caminiti",
    firm: "",
    email: "dcaminiti@breslinandbreslin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-351",
  },
  {
    firstName: "Susan",
    lastName: "Karp",
    firm: "",
    email: "skarp@murphyllp.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-352",
  },
  {
    firstName: "Denis",
    lastName: "Murphy",
    firm: "",
    email: "dmurphy@weiner.law",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-353",
  },
  {
    firstName: "Carmine",
    lastName: "Villani",
    firm: "",
    email: "crvillani@villanideluca.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-354",
  },
  {
    firstName: "Eric",
    lastName: "Katz",
    firm: "",
    email: "ekatz@mazieslater.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-355",
  },
  {
    firstName: "Joe",
    lastName: "Valenti",
    firm: "",
    email: "jvalenti@parkermccay.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-356",
  },
  {
    firstName: "Sheila",
    lastName: "Mints",
    firm: "",
    email: "smints@parkermccay.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-357",
  },
  {
    firstName: "Rick",
    lastName: "Cushman",
    firm: "",
    email: "rcushman@parkermccay.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-358",
  },
  {
    firstName: "Sean",
    lastName: "Fannon",
    firm: "",
    email: "sfannon@parkermccay.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-359",
  },
  {
    firstName: "Daniele",
    lastName: "Capecci",
    firm: "",
    email: "dcapecci@parkermccay.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-360",
  },
  {
    firstName: "Stuart",
    lastName: "Wilkins",
    firm: "",
    email: "stuartwilkins62@outlook.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-361",
  },
  {
    firstName: "Randy",
    lastName: "Lafferty",
    firm: "",
    email: "rlafferty@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-362",
  },
  {
    firstName: "Lisa",
    lastName: "Parker",
    firm: "",
    email: "lparker@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-363",
  },
  {
    firstName: "Jeffrey",
    lastName: "Puff",
    firm: "",
    email: "jvppuff@comcast.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-364",
  },
  {
    firstName: "Jaice",
    lastName: "Jacob",
    firm: "",
    email: "jaice@thomasvallen.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-365",
  },
  {
    firstName: "Jonathan",
    lastName: "Wolfe",
    firm: "",
    email: "jwolfe@skoloffwolfe.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-366",
  },
  {
    firstName: "Michael",
    lastName: "Morea",
    firm: "Morea Law",
    email: "michael.morea@morealaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-367",
  },
  {
    firstName: "Francisco",
    lastName: "Rodriguez",
    firm: "",
    email: "frodriguez@javerbaumwurgaft.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-368",
  },
  {
    firstName: "Cory",
    lastName: "Rothbort",
    firm: "",
    email: "crothbort@mazieslater.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-369",
  },
  {
    firstName: "Mike",
    lastName: "Mumola",
    firm: "",
    email: "mmumola@kmhlawyers.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-370",
  },
  {
    firstName: "Tom",
    lastName: "Shebell",
    firm: "",
    email: "tshebell@shebell.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-371",
  },
  {
    firstName: "Emily",
    lastName: "Santana",
    firm: "",
    email: "esantana@reitlerlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-372",
  },
  {
    firstName: "Abhishek",
    lastName: "Bapna",
    firm: "",
    email: "abapna@pbwt.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-373",
  },
  {
    firstName: "Derek",
    lastName: "Reed",
    firm: "",
    email: "dreed@epgprlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-374",
  },
  {
    firstName: "Regina",
    lastName: "Spielberg",
    firm: "",
    email: "rms@spsk.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-375",
  },
  {
    firstName: "Nicholas",
    lastName: "Giuditta",
    firm: "",
    email: "nick@giudittalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-376",
  },
  {
    firstName: "Dillon",
    lastName: "McGuire",
    firm: "",
    email: "dmcguire@pashmanstein.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-377",
  },
  {
    firstName: "Robert",
    lastName: "Tarver",
    firm: "",
    email: "tarverlaw@comcast.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-378",
  },
  {
    firstName: "Fred",
    lastName: "Greenberg",
    firm: "",
    email: "fred@fredgreenberg.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-379",
  },
  {
    firstName: "Jonathan",
    lastName: "Lerner",
    firm: "",
    email: "jlerner@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-380",
  },
  {
    firstName: "Tatiana",
    lastName: "Laing",
    firm: "",
    email: "tlaing@paulweiss.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-381",
  },
  {
    firstName: "Alan",
    lastName: "Pralgever",
    firm: "",
    email: "apralgever@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-382",
  },
  {
    firstName: "Robert",
    lastName: "Schachter",
    firm: "",
    email: "rschachter@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-383",
  },
  {
    firstName: "David",
    lastName: "Bruck",
    firm: "",
    email: "dbruck@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-384",
  },
  {
    firstName: "Kirsten",
    lastName: "Kortbawi",
    firm: "",
    email: "kkortbawi@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-385",
  },
  {
    firstName: "Diana",
    lastName: "Parker",
    firm: "",
    email: "dparker@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-386",
  },
  {
    firstName: "Ellen",
    lastName: "Amon",
    firm: "",
    email: "eamon@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-387",
  },
  {
    firstName: "Dennis",
    lastName: "Estis",
    firm: "",
    email: "estis@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-388",
  },
  {
    firstName: "Joel",
    lastName: "Clymer",
    firm: "",
    email: "jclymer@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-389",
  },
  {
    firstName: "Pierson",
    lastName: "Backes",
    firm: "",
    email: "pb@backesfirm.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-390",
  },
  {
    firstName: "Reginald",
    lastName: "Long",
    firm: "",
    email: "rlong@loveandlonglaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-391",
  },
  {
    firstName: "Arif",
    lastName: "Gozel",
    firm: "",
    email: "arif@gozellaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-392",
  },
  {
    firstName: "David",
    lastName: "Stone",
    firm: "",
    email: "davids@stonemagnalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-393",
  },
  {
    firstName: "Carolyn",
    lastName: "Daly",
    firm: "",
    email: "cdaly@dalyfamilylaw.net",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-394",
  },
  {
    firstName: "Jennifer",
    lastName: "Mohamed",
    firm: "",
    email: "jennifer@baynelaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-395",
  },
  {
    firstName: "Chad",
    lastName: "Rutkowski",
    firm: "",
    email: "crutkowski@bakerlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-396",
  },
  {
    firstName: "Margaret",
    lastName: "Keavney",
    firm: "",
    email: "margaret@keavneystreger.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-397",
  },
  {
    firstName: "Stephen",
    lastName: "DeNittis",
    firm: "",
    email: "sdenittis@denittislaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-398",
  },
  {
    firstName: "Marc",
    lastName: "Schauer",
    firm: "",
    email: "mschauer@wcmlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-399",
  },
  {
    firstName: "John",
    lastName: "Whipple",
    firm: "",
    email: "jcwhipple@whippleazzarellolaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-400",
  },
  {
    firstName: "L Grace",
    lastName: "Spencer",
    firm: "",
    email: "ls@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-401",
  },
  {
    firstName: "Christopher",
    lastName: "Conrad",
    firm: "",
    email: "cconrad@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-402",
  },
  {
    firstName: "Robert",
    lastName: "Banas",
    firm: "",
    email: "rbanas@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-403",
  },
  {
    firstName: "Bill",
    lastName: "Crutchlow",
    firm: "",
    email: "bcrutchlow@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-404",
  },
  {
    firstName: "Daryl",
    lastName: "Zaslow",
    firm: "",
    email: "dzaslow@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-405",
  },
  {
    firstName: "Edward",
    lastName: "McElroy",
    firm: "",
    email: "emcelroy@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-406",
  },
  {
    firstName: "Thomas",
    lastName: "Rinaldi",
    firm: "",
    email: "trinaldi@njadvocates.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-407",
  },
  {
    firstName: "Robert",
    lastName: "Snellings",
    firm: "",
    email: "snelliro@yahoo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-408",
  },
  {
    firstName: "John",
    lastName: "Fazzio",
    firm: "",
    email: "jfazzio@fazziolaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-409",
  },
  {
    firstName: "Michael",
    lastName: "Berger",
    firm: "",
    email: "mberger@andresberger.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-410",
  },
  {
    firstName: "Chris",
    lastName: "Musmanno",
    firm: "",
    email: "cmusmanno@einhornlawyers.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-411",
  },
  {
    firstName: "Thomas",
    lastName: "Major",
    firm: "",
    email: "tmajor@offitkurman.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-412",
  },
  {
    firstName: "Howard",
    lastName: "Leopold",
    firm: "",
    email: "howard@hleopoldlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-413",
  },
  {
    firstName: "Stuart",
    lastName: "Minion",
    firm: "",
    email: "ssherman@minionsherman.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-414",
  },
  {
    firstName: "Kenneth",
    lastName: "Andres",
    firm: "",
    email: "kandres@andresberger.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-415",
  },
  {
    firstName: "Randy",
    lastName: "Lafferty",
    firm: "",
    email: "rlafferty@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-416",
  },
  {
    firstName: "Brian",
    lastName: "Barr",
    firm: "",
    email: "bbarr@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-417",
  },
  {
    firstName: "Scott",
    lastName: "Good",
    firm: "",
    email: "sgood@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-418",
  },
  {
    firstName: "Michael",
    lastName: "Salad",
    firm: "",
    email: "msalad@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-419",
  },
  {
    firstName: "Nicholas",
    lastName: "Talvacchia",
    firm: "",
    email: "ntalvacchia@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-420",
  },
  {
    firstName: "Eric",
    lastName: "Browndorf",
    firm: "",
    email: "e.browndorf@cooperlevenson.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-421",
  },
  {
    firstName: "Andrew",
    lastName: "Chambray",
    firm: "",
    email: "achambarry@gillandchamas.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-422",
  },
  {
    firstName: "David",
    lastName: "Lande",
    firm: "",
    email: "dlande@gillandchamas.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-423",
  },
  {
    firstName: "Michael",
    lastName: "Hanus",
    firm: "",
    email: "mhanus@gillandchamas.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-424",
  },
  {
    firstName: "Michael",
    lastName: "Rosenberg",
    firm: "",
    email: "mrose@gillandchamas.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-425",
  },
  {
    firstName: "Robert",
    lastName: "Baranowski",
    firm: "",
    email: "baranowski@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-426",
  },
  {
    firstName: "Stacy",
    lastName: "Asbell",
    firm: "",
    email: "asbell@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-427",
  },
  {
    firstName: "Mark",
    lastName: "Shapiro",
    firm: "",
    email: "shapiro@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-428",
  },
  {
    firstName: "Jennifer",
    lastName: "Cordes",
    firm: "",
    email: "cordes@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-429",
  },
  {
    firstName: "Zachary",
    lastName: "Friedman",
    firm: "",
    email: "friedman@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-430",
  },
  {
    firstName: "Megan",
    lastName: "Balne",
    firm: "",
    email: "balne@hylandlevin.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-431",
  },
  {
    firstName: "Kasia",
    lastName: "Zielinski",
    firm: "",
    email: "kasia@mezlawyers.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-432",
  },
  {
    firstName: "Adam",
    lastName: "Eisenhut",
    firm: "",
    email: "adam@mezlawyers.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-433",
  },
  {
    firstName: "Tricia",
    lastName: "McNally",
    firm: "",
    email: "tricia@mezlawyers.com",
    city: "",
    state: "",
    signupCode: "novolens-nj24-434",
  },
  {
    firstName: "John",
    lastName: "Brost",
    firm: "",
    email: "jbrost@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-435",
  },
  {
    firstName: "Alona",
    lastName: "Magidova",
    firm: "",
    email: "amagidova@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-436",
  },
  {
    firstName: "David",
    lastName: "Wendel",
    firm: "",
    email: "dwendel@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-437",
  },
  {
    firstName: "Juliana",
    lastName: "Diaz",
    firm: "",
    email: "juliana.diaz1@gmail.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-438",
  },
  {
    firstName: "Henry",
    lastName: "Cistrelli",
    firm: "",
    email: "hcistrelli@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-439",
  },
  {
    firstName: "Robert",
    lastName: "Hille",
    firm: "",
    email: "rhille@greenbaumlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-440",
  },
  {
    firstName: "Stephen",
    lastName: "Urbinato",
    firm: "",
    email: "surbinato@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-441",
  },
  {
    firstName: "Ira",
    lastName: "Starr",
    firm: "",
    email: "irastarr@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-442",
  },
  {
    firstName: "Ana Rita",
    lastName: "Ferreira",
    firm: "",
    email: "ferreiraa@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-443",
  },
  {
    firstName: "Bruce",
    lastName: "Pitman",
    firm: "",
    email: "bpitman@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-444",
  },
  {
    firstName: "Henry",
    lastName: "Cistrelli",
    firm: "",
    email: "hcistrelli@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-445",
  },
  {
    firstName: "Stephen",
    lastName: "Barry",
    firm: "Barry, Corrado, Grassi & Gibson, PC",
    email: "sbarry@capelegal.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-446",
  },
  {
    firstName: "Joshua",
    lastName: "Donohue",
    firm: "Barry, Corrado, Grassi & Gibson, PC",
    email: "jdonohue@capelegal.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-447",
  },
  {
    firstName: "Stephen",
    lastName: "Joseph",
    firm: "",
    email: "vegasshj@yahoo.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-448",
  },
  {
    firstName: "Steven",
    lastName: "Goldberg",
    firm: "",
    email: "sgoldenberg@ghclaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-449",
  },
  {
    firstName: "Aaron",
    lastName: "Bayram",
    firm: "",
    email: "aaronb@jonallaw.com",
    city: "",
    state: "NY",
    signupCode: "novolens-nj24-450",
  },
  {
    firstName: "Enes",
    lastName: "Hajdarpasic",
    firm: "",
    email: "eneshajdar@gmail.com",
    city: "",
    state: "NY",
    signupCode: "novolens-nj24-451",
  },
  {
    firstName: "Catherine",
    lastName: "Grohe",
    firm: "",
    email: "cshiels@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-452",
  },
  {
    firstName: "Hristo",
    lastName: "Zaevlikaris",
    firm: "",
    email: "czevlikaris@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-453",
  },
  {
    firstName: "Eric",
    lastName: "Schlesinger",
    firm: "",
    email: "eschlesinger@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-454",
  },
  {
    firstName: "Meghan",
    lastName: "Ayre",
    firm: "",
    email: "mayre@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-455",
  },
  {
    firstName: "Rosanne",
    lastName: "Palumbo",
    firm: "",
    email: "rpalumbo@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-456",
  },
  {
    firstName: "Deborah",
    lastName: "Banfield",
    firm: "",
    email: "dbanfield@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-457",
  },
  {
    firstName: "Loren",
    lastName: "Solari",
    firm: "",
    email: "lsolari@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-458",
  },
  {
    firstName: "Rey",
    lastName: "Vilanueva",
    firm: "",
    email: "rvillanueva@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-459",
  },
  {
    firstName: "Jeffrey",
    lastName: "Bell",
    firm: "",
    email: "jbell@grsl.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-460",
  },
  {
    firstName: "Michael",
    lastName: "Kulzer",
    firm: "",
    email: "mkulzer@kulzerdipadova.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-461",
  },
  {
    firstName: "Steven",
    lastName: "Petrillo",
    firm: "",
    email: "spetrillo@petrilloandgoldberg.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-462",
  },
  {
    firstName: "Katelyn",
    lastName: "Cutinello",
    firm: "",
    email: "katelyn@coccalaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-463",
  },
  {
    firstName: "William",
    lastName: "Barrett",
    firm: "",
    email: "william.barrett@rocketmail.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-464",
  },
  {
    firstName: "James",
    lastName: "Pantages",
    firm: "",
    email: "jpantages@fgsb.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-465",
  },
  {
    firstName: "Richard",
    lastName: "Reinartz",
    firm: "",
    email: "rich@reinartzlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-466",
  },
  {
    firstName: "Andrew",
    lastName: "Fraser",
    firm: "",
    email: "afraser@lcrlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-467",
  },
  {
    firstName: "Stephen",
    lastName: "Knox",
    firm: "",
    email: "sknox@bressler.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-468",
  },
  {
    firstName: "Chris",
    lastName: "Pyne",
    firm: "",
    email: "cpyne@stark-stark.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-469",
  },
  {
    firstName: "John",
    lastName: "Burke",
    firm: "",
    email: "jburke@kbblegal.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-470",
  },
  {
    firstName: "Tom",
    lastName: "McKinney",
    firm: "",
    email: "tom@cmlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-471",
  },
  {
    firstName: "John",
    lastName: "Hein",
    firm: "",
    email: "jhein@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-472",
  },
  {
    firstName: "Brant",
    lastName: "Kuehn",
    firm: "",
    email: "bkuehn@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-473",
  },
  {
    firstName: "Paul",
    lastName: "DeFilippo",
    firm: "",
    email: "pdefilippo@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-474",
  },
  {
    firstName: "Brad",
    lastName: "Axelrod",
    firm: "",
    email: "baxelrod@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-475",
  },
  {
    firstName: "David",
    lastName: "Wollmuth",
    firm: "",
    email: "dwollmuth@wmd-law.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-476",
  },
  {
    firstName: "Robert",
    lastName: "Fuggi",
    firm: "",
    email: "robert@fuggilaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-477",
  },
  {
    firstName: "Tanis",
    lastName: "Deitch",
    firm: "",
    email: "tdeitch@deitchandperone.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-478",
  },
  {
    firstName: "Vincent",
    lastName: "Maltese",
    firm: "",
    email: "maltesev@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-479",
  },
  {
    firstName: "John",
    lastName: "Keefe",
    firm: "",
    email: "jkeefe@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-480",
  },
  {
    firstName: "David",
    lastName: "Wildstein",
    firm: "",
    email: "dwildstein@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-481",
  },
  {
    firstName: "Alex",
    lastName: "Lyubarsky",
    firm: "",
    email: "alyubarsky@wilentz.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-482",
  },
  {
    firstName: "Gary",
    lastName: "Shapiro",
    firm: "",
    email: "gshapiro@shapirosternlieb.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-483",
  },
  {
    firstName: "Charles",
    lastName: "Vuotto",
    firm: "",
    email: "cvuotto@starrgern.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-484",
  },
  {
    firstName: "Diane",
    lastName: "Alexander",
    firm: "",
    email: "dalexander@mfhenvlaw.com",
    city: "",
    state: "NJ",
    signupCode: "novolens-nj24-485",
  },
];

module.exports = Object.freeze({
  trialUsers: trialUsers,
});
